version: '3.8'

services:
  sqlserver:
    build:
      context: ./Docker
      dockerfile: sql.Dockerfile
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASSWORD}
    volumes:
      - sqlserver_data:/var/opt/mssql

  webapi:
    container_name: webapi
    build:
      context: .
      dockerfile: src/WebAPI/Dockerfile
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:${API_PORT}
      - ConnectionStrings__SqlServer=Server=host.docker.internal;Database=${DB_NAME};User Id=${DB_USER};Password=${DB_PASSWORD};TrustServerCertificate=True

  frontend:
    container_name: frontend
    build:
      context: ./src/React
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    volumes:
      - ./src/React:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:${API_PORT}/api
    depends_on:
      - webapi

volumes:
  sqlserver_data: 